pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - "#approved-reviews-by>=2"
      - "check-success=Codacy Static Code Analysis"
      - "check-success=Semantic PR"
      - "base=develop"
    actions:
      merge:
